### ISSUE TITLE
데이터 정리 - 산 데이터 권역별 분류

### ISSUE THREAD

**Issue by yongheon-Lee** [joong8812/mooyaho#169]
100대 명산 데이터를 권역별로 분류해 추후 서비스 개선에 활용할 준비를 하고자 합니다.

**Comment by yongheon-Lee** [comment]
코드 작성해서 분류하려고 했지만, 지역명 내 권역이 섞여있는 곳이 많았습니다. 그래서 산림청 홈페이지에서 100대 명산 목록 및 지도를 통해 수기로 데이터에 채워 넣었습니다.

**Comment by joong8812** [comment]
> 코드 작성해서 분류하려고 했지만, 지역명 내 권역이 섞여있는 곳이 많았습니다. 그래서 산림청 홈페이지에서 100대 명산 목록 및 지도를 통해 수기로 데이터에 채워 넣었습니다.

우옹 ㅠ-ㅠ 고생하셨네요 👍
